[build]
  command = "pip install -r requirements.txt"
  publish = "web_dynamic/templates"

[build.environment]
  PYTHON_VERSION = "3.8"

[build.processing]
  skip_processing = true

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
  force = true
  headers = { X-Proxy-Route = "/" }

[[redirects]]
  from = "/about_us"
  to = "/about_us.html"
  status = 200
  force = true
  headers = { X-Proxy-Route = "/about_us" }

[[redirects]]
  from = "/translations"
  to = "/translations.html"
  status = 200
  force = true
  headers = { X-Proxy-Route = "/translations" }

[[redirects]]
  from = "/sign-up"
  to = "/index.html"
  status = 200
  force = true
  headers = { X-Proxy-Route = "/sign-up" }

[[redirects]]
  from = "/subscribe"
  to = "/subscription_success.html"
  status = 200
  force = true
  headers = { X-Proxy-Route = "/subscribe" }

[[redirects]]
  from = "/my_account/translations_history"
  to = "/translations_history.html"
  status = 200
  force = true

[[redirects]]
  from = "/my_account/settings"
  to = "/settings.html"
  status = 200
  force = true

[[redirects]]
  from = "/languages"
  to = "/languages.html"
  status = 200
  force = true


[[redirects]]
  from = "/privacy_terms"
  to = "/privacy_terms.html"
  status = 200
  force = true
  headers = { X-Proxy-Route = "/privacy_terms" }

[[redirects]]
  from = "/my_account"
  to = "/my_account.html"
  status = 200
  force = true
  headers = { X-Proxy-Route = "/my_account" }

[[redirects]]
  from = "/sign_in"
  to = "/index.html"
  status = 200
  force = true
  headers = { X-Proxy-Route = "/sign_in" }

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200
  force = true
  headers = { X-Proxy-Route = "/login" }

[[redirects]]
  from = "/payment"
  to = "/payment.html"
  status = 200
  force = true
  headers = { X-Proxy-Route = "/payment"}

[[redirects]]
  from = "/styles/:splat"
  to = "/styles/*/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/scripts/:splat"
  to = "/scripts/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/images/:splat"
  to = "/images/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/v1/*"
  to = "http://localhost:5000/:splat"
  status = 200
  force = true
  headers = { X-Proxy-Pass = "/api/v1" }
