#!/usr/bin/python3
"""
Text translator
"""
import json
import translator
import uuid
from translator.translation_model import TranslationModel, Base
from os import getenv
import sqlalchemy
from sqlalchemy import Column, String, ForeignKey, Text


class AllTranslations(TranslationModel, Base):

    if translator.storage_type == "db":
        __tablename__ = "translations"
        id = Column(String(60), ForeignKey("translation.id"), primary_key=True)
        input_data = Column(String(4500), nullable=False)
        source_lang = Column(String(50), nullable=False)
        target_lang = Column(String(50), nullable=False)
        translated_data = Column(Text, nullable=False)

    else:
        id = ""
        input_data = ""
        source_lang = ""
        target_lang = ""
        translated_data = ""

    def __init__(self, *args, **kwargs):
        """initializes all translations"""
        super().__init__(*args, **kwargs)
